name: Periodic ping

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      id: hello
      uses: srt32/uptime@958231f4d95c117f08eb0fc70907e80d0dfedf2b
      with:
        url-to-hit: "https://example.com"
        expected-statuses: "200,301"